import {
  RENDERER_TARGETS_HTML_MERMAID_NODE_REQUIRED,
  RENDERER_TARGETS_HTML_MERMAID_RENDER_FAILED,
  RENDERER_TARGETS_HTML_UNKNOWN_BLOCK_TYPE,
} from "../src/diagnostic-codes.js";
import type { HtmlRenderCase } from "./render-case.js";

export const renderCases: HtmlRenderCase[] = [
  {
    id: "minimal-en",
    document: "valid/minimal.airp.json",
    entry: "isomorphic",
    expect: {
      ok: true,
      contains: [
        "<!DOCTYPE html>",
        "<title>Minimal report</title>",
        'lang="en"',
        "Hello AIRP.",
        'data-block-type="paragraph"',
        'data-route-path="/"',
        "AIRP Renderer",
        "AI Report Protocol v1.0.0",
        "v1.1.4",
        "data-doc-header",
      ],
      notContains: [
        "data-doc-kind",
        'data-page-toc="true"',
        "AIRP v1.0.0",
        "data-app-version",
      ],
    },
  },
  {
    id: "minimal-1.1.0-en",
    document: "valid/minimal-1.1.0.airp.json",
    entry: "isomorphic",
    expect: {
      ok: true,
      contains: [
        "<title>Minimal report 1.1.0</title>",
        "Hello AIRP 1.1.0.",
        "AI Report Protocol v1.1.0",
        "Last updated",
        "data-doc-last-updated",
        'data-doc-time-by="maosong"',
        "data-doc-time",
      ],
      notContains: [
        "data-doc-authors",
        "data-doc-kind",
        "AI Report Protocol v1.0.0",
      ],
    },
  },
  {
    id: "minimal-1.1.0-zh",
    document: "valid/minimal-1.1.0-zh.airp.json",
    entry: "isomorphic",
    expect: {
      ok: true,
      contains: [
        "<title>最小报告 1.1.0</title>",
        "最后更新",
        "data-doc-last-updated",
        'data-doc-time-by="maosong"',
      ],
      notContains: ["data-doc-authors"],
    },
  },
  {
    id: "section-at-id-1.1.0",
    document: "valid/section-at-id-1.1.0.airp.json",
    entry: "isomorphic",
    expect: {
      ok: true,
      contains: [
        'id="aaaaaaaaaa"',
        'id="cccccccccc"',
        'href="#aaaaaaaaaa"',
        'href="#cccccccccc"',
        'id="ffffffffff"',
        "[1]",
        "[2]",
        "First source",
        "Second source",
        "<strong",
        "<em",
        "<del",
        "<code",
        'href="https://example.com"',
        "var(--code-bg)",
        "var(--text-muted)",
        ">alpha<",
        ">beta<",
      ],
      notContains: ['id="cite-', "hello-world", "section-1"],
      hasSectionAnchors: true,
      hasPageToc: true,
    },
  },
  {
    id: "html-blocks-en",
    document: "valid/html-blocks.airp.json",
    entry: "node",
    expect: {
      ok: true,
      contains: [
        "<title>HTML block coverage</title>",
        "Phase 3b fixture",
        'data-block-type="hero"',
        "Key metrics",
        'data-block-type="section"',
        'data-block-type="mermaid"',
        'data-mermaid="true"',
        'id="airp-mmd-0"',
        'id="airp-mmd-1"',
        'data-block-type="architectureOverview"',
        'data-block-type="embed"',
        "data-embed-card",
        'data-block-type="agentNote"',
        "Visible agent note for human readers.",
        'data-block-type="image"',
        'data-block-type="collection"',
        'data-block-type="tabs"',
        'data-tabs-tab="true"',
        'data-storage-key="airp-tabs:/:tabs-1"',
        'data-default-panel="panel-1"',
        'data-block-type="collapsible"',
        'data-collapsible-trigger="true"',
        'data-storage-key="airp-collapsible:/:collapsible-1"',
        'data-default-open="true"',
        'href="#airp-icon-chevron-down"',
        'data-block-type="appendix"',
        "AIRP Renderer",
        "data-code-copy",
        'data-code-diff="unified"',
        'data-code-diff="split"',
        'data-code-diff-line="add"',
        'data-code-diff-line="del"',
        "shiki",
        "data-doc-time",
        "status-badge",
        'data-status="',
        'data-max-columns="3"',
        'data-doc-sources-menu-trigger="true"',
        'data-doc-sources-menu-panel="true"',
        'data-doc-sources-menu="true"',
        'id="app-color-scheme-toggle"',
        "Rigid",
        "Scope: html-target",
        "Evidence",
      ],
      notContains: [
        "Hidden agent note.",
        "Default-hidden",
        "data-mermaid-source",
        "data-mermaid-placeholder",
        "data-doc-kind",
        'data-page-toc="true"',
        "block-skin-",
        "basecoat",
        "data-code-dots",
        "data-callout-variant",
        "nonNegotiable:",
      ],
      hasSvgViewer: true,
      hasSectionAnchors: true,
      hasHeroMetricTones: true,
      hasInteractiveTabs: true,
      hasAgentNoteChrome: true,
      hasAppendixTitleOnly: true,
    },
  },
  {
    id: "page-toc-en",
    document: "valid/page-toc.airp.json",
    entry: "isomorphic",
    expect: {
      ok: true,
      contains: [
        'data-page-toc="true"',
        'data-page-toc-mini="true"',
        'data-page-toc-panel="true"',
        'href="#overview"',
        'href="#details"',
        'href="#notes"',
        'href="#closing"',
        'data-toc-level="1"',
        'data-toc-level="2"',
        'data-toc-level="3"',
        "On this page",
      ],
      hasSectionAnchors: true,
      hasPageToc: true,
    },
  },
  {
    id: "extra-app-header-slot",
    document: "valid/minimal.airp.json",
    entry: "isomorphic",
    targetOptions: {
      extraAppHeader:
        '<button type="button" data-test-extra-app-header="true">Host</button>',
      extraHeadPre: "<!-- airp-test-extra-head-pre -->",
      extraHead: "<!-- airp-test-extra-head -->",
      extraBody: "<!-- airp-test-extra-body -->",
    },
    expect: {
      ok: true,
      contains: [
        'data-test-extra-app-header="true"',
        "<!-- airp-test-extra-head-pre -->",
        "<!-- airp-test-extra-head -->",
        "<!-- airp-test-extra-body -->",
        "data-extra-app-header",
        "data-app-header-trailing",
      ],
      hasExtraAppHeader: true,
      hasExtraHeadPre: true,
    },
  },
  {
    id: "mermaid-ok-node",
    document: "valid/mermaid-ok.airp.json",
    entry: "node",
    expect: {
      ok: true,
      contains: [
        'data-block-type="mermaid"',
        'id="airp-mmd-0"',
        'id="airp-mmd-1"',
        'data-mermaid="true"',
        'data-storage-key="airp-svg-viewer:/:mermaid-1"',
        'data-storage-key="airp-svg-viewer:/:mermaid-2"',
      ],
      notContains: ["data-mermaid-source"],
      hasSvgViewer: true,
      distinctMermaidSvgIds: true,
    },
  },
  {
    id: "mermaid-bad-source-soft-fail",
    document: "valid/mermaid-bad-source.airp.json",
    entry: "node",
    expect: {
      ok: true,
      contains: [
        "Before diagram.",
        "After diagram.",
        'data-mermaid-error="true"',
        "Mermaid render failed",
      ],
      notContains: ["data-mermaid-source"],
      diagnostics: [
        {
          code: RENDERER_TARGETS_HTML_MERMAID_RENDER_FAILED.code,
          severity: "warning",
        },
      ],
    },
  },
  {
    id: "mermaid-ok-1.1.0-storage-key",
    document: "valid/mermaid-ok-1.1.0.airp.json",
    entry: "node",
    expect: {
      ok: true,
      contains: [
        'data-block-type="mermaid"',
        'data-storage-key="airp-svg-viewer:/:mmmmmmmmmm"',
        'data-storage-key="airp-svg-viewer:/:oooooooooo"',
        'data-storage-key="airp-collapsible:/:cccccccccc"',
        'data-default-open="false"',
        'data-storage-key="airp-tabs:/:tttttttttt"',
        'data-default-panel="qqqqqqqqqq"',
        'data-tabs-panel-key="ssssssssss"',
      ],
      notContains: [
        'data-storage-key="airp-svg-viewer:/:mermaid-1"',
        'data-storage-key="airp-svg-viewer:/:aaaaaaaaaa"',
        'data-storage-key="airp-collapsible:/:collapsible-1"',
        'data-storage-key="airp-tabs:/:tabs-1"',
      ],
      hasSvgViewer: true,
      distinctMermaidSvgIds: true,
    },
  },
  {
    id: "mermaid-node-required",
    document: "valid/mermaid-ok.airp.json",
    entry: "isomorphic",
    expect: {
      ok: false,
      code: RENDERER_TARGETS_HTML_MERMAID_NODE_REQUIRED.code,
    },
  },
  {
    id: "markdown-blocks-agent-note",
    document: "valid/markdown-blocks.airp.json",
    entry: "node",
    expect: {
      ok: true,
      contains: ["Visible note", 'data-block-type="table"'],
      notContains: ["Hidden note", "Default-hidden note"],
    },
  },
  {
    id: "unknown-block-type",
    document: "invalid/unknown-block-type.airp.json",
    entry: "isomorphic",
    expect: {
      ok: false,
      code: RENDERER_TARGETS_HTML_UNKNOWN_BLOCK_TYPE.code,
    },
  },
];
